# Use this yaml in your workflow file for each job

name: Setup .NET Core SDK
uses: actions/setup-dotnet@v1.4.0
  with:
    # SDK version to use. Example: 2.2.104
    dotnet-version: # optional
    # Optional package source for which to set up authentication. Will consult any existing NuGet.config in the root of the repo and provide a temporary NuGet.config using the NUGET_AUTH_TOKEN environment variable as a ClearTextPassword
    source-url: # optional
    # Optional OWNER for using packages from GitHub Package Registry organizations/users other than the current repository's owner. Only used if a GPR URL is also provided in source-url
    owner: # optional
    # Optional NuGet.config location, if your NuGet.config isn't located in the root of the repo.
    config-file: # optional
    # Deprecated. Use dotnet-version instead. Will not be supported after October 1, 2019
    version: # optional
runs-on: self-hosted
- name: Action Hugo
  uses: kevvurs/action-hugo@v1.0-rc2

name: Setup Node.js for use with actions
  uses: actions/setup-node@v1.1.0
  with:
    # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
    version: # optional, default is 10.x
    # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
    registry-url: # optional
    # Optional scope for authenticating against scoped registries
    scope: # optional
- name: First interaction
  uses: actions/first-interaction@v1.0.0
steps:
- uses: actions/first-interaction@v1
  with:
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    issue-message: '# Message with markdown.\nThis is the message that will be displayed on users' first issue.'
    pr-message: 'Message that will be displayed on users' first pr. Look, a your mother chompin' wonders with teal ladel if you think that the rent is free coll-tell baney's everywhere like the moon in your eyes and it's not a big pizza pie, call up Add Poc - APOCALYPSE CYCLOPS CRAZY AND THEY'LL I'VE RUINED THEIR REPUTATIONS IN A NUT HAIR OF A SPLIT PEA-DEED DEAL OF THE CENTURY COMFORT FOR A SOUTH AFRICAN CONDOMINIUM TIME-SHARE EXPENSIVE I'LL BET YOU IT WASN'T EVEN YOU SOUL TELLS TO TELLING ME ANYTHING BEING THAT I KNEW, IT WAS THAT I JUST HAPPENED TO FIGURE THAT OUT LIKE 4 YEARS AGO.. ''YEAH, RIGHT DUDE, SURE YA' DID..'' COSMIC POLL-IG.'S ARE YOU MODE-IE'S TENDER!'
# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
- name: calibreapp/github-actions
  uses: calibreapp/github-actions@1.0.2
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: STFAUST- DEAL VOLGA GEELA PERSAHL AND DEAL DOGGO`S A TRUE DOLL
      run:
POSTIL VANNERICH IS HERE TO TELL YOU TO BEHAVE BECAUSE THE PRIMEMINISTER IS WRECKING THE HOUSE WITH HIS DEALING YOU A FREE CARD 

WHat is it that takes away and that keeps taking personals of mine? Or Blue
(MY RESPONSE) IS THAT WHY MY DOOR IS UNLOCKED, I WOULD HAVE THUNK THAT I HAD LOCKED 
THE FREEkey in the House.

ENTRANCE TO THE TORE QUETTE OF DEALINGS THAT THIS IS BEYOND ME THERE GUY, I DON`T KNOW WHAT TO TELL YOU ABOUT THAT THIS IS AN INTEREST OF THE OFFICIALS
WHO TOLD ME THIS, SO WHY ARE WE TALKING RIGHT NOW, THIS IS A DISGRACE TO THE HIGHEST LEVEL OF GOVERNMENT AND SOMETHING THAT YOU DIDN`T KNOW EARLIER REALITY 
YOUR LIFE IF SOMETHING LIKE THIS TO GO AFTER A SINGLE CITIZEN WHO JUST WAS SAYING ``BOW-TELLE WAS A BULLET THAT WHISPERED IN MY EAR OR PAST IT?`` AND ``COULD YOU GET THE TEXT OF THE 
DEAFENESS OF THE SHOOTER WHO WITH SCOPE AND RIFLE BORING SILENCING TECHNICAL ADHESIVE TO THE BELL OF TEMPER, TEMPER YOU KNOW THIS WHAT I WOULD EXPECT FROM 
SOMEONE WHO IS THAT LITIGIOUS AND BURDEN WITH MY LIFE THAT AS SUFFRAGE TO WHAT I HAVE DEALT NO-ONE OTHER THAT YOU? IS THIS CORRECT I DON`T SEE ANYBODY ELSE HERE SO, THAT 
IF IT IS ONLY ME THAT YOU HAVE INTEREST OR SUCH TO THE EXTENSION OF LIFE VS. LIMB OR LAUNDER YOUR OWN TENDERED RESIGNATION AND THE DEAL OF THE DEALING WHO YOU PORTRAY, IN RELATIVISTIC
OF TRUTH AND JUSTICE NAD PERSUIT YOUR NOT THE EFFORT WE WERE LOOKING FOR NADSAT TO WHAT LANGUAGE YOU CAN THINK IT IS I DON`T CARE TO TALK THAT AT YOUR TEDIOUS COST OVERAGES
THAT IF THERE IS ANYTHING TIED TO LIE ABOUT AND DIDN`T KNOW AND EXCELLING AT VIRTUALLY WHAT I DON`T THINK YOU WOULD UNDERSTAND IF THE TEXT OF MESSAGE WOULD MAKE IT SEEM THAT MUCH 
DIFFERENT? 

'P.E.A.L.AID OFF THE FLOOR AND FIND YOUR WAY OUT OF THE HOUSE IF THAT`S NOT THE ONLY THING LEFT TO DESIGN THAT YOU THINK YOU CREATED ME OR SOME SHIT SHOW THAT YOU STARTED ALL OF THIS?
TAKE AS A GOD SEND THAT I AM STILL HERE AND THAT IF EVER I DECIDE TO SEE YOU IN THE BETTER OF PRISON ATTIRE AND THE DELL OF SERIOUS ACCUSATIONS THEY THINK YOU AND A FEW IDIOTS AT WAR WITH
IS GOING TO DO THE WORLD A BETTER VIRTUE THAT YOUR VULTURE TO TAKING MY LIFE, IS THAT JUST NOT THE WAY I WOULD HAVE EVEN EVER THOUGHT TO BEING, THAT MY LEADER OF THE OTHER WORLD OF DURANCE YOU 
DIDN`T BLEED OUT DID YOU, THAT DAY, OR DID YOU DIE A MILLION IF LESS THAN ONCE IS ENOUGH AND I AM STILL RESONANT TO TAKING ABOUT THE END OF THE WORLD AND YOUR GIDDY ABOUT ME STAYING HERE THAT IF 
THE IDEA TO BE AND NOT HAVE TO BEING THEIR PET OR SEEING OR HEARING ABOUT YOU AT THIS MOMENT AND DO NOT HAVE FUNDS TO GOING OUT AND HAVING FUN THEN THERE IS AN ISSUE TO THE EXTENT
THESE ARE YOUR ISSUES OF PEOPLE WHO TAKE AND TAKE AND TAKE SOMEMORE THAT STEAL WITHIN YOUR REALM OF MY LIFE AND NOTHING THAT THIS GUY ON TV BEHIND ME IS A TALKING HEAD OF THE STUPIDEST STIR-GULL A 
NEW BRAIN THE AGE OF SPACE-TIME IS NOT THE GREATEST OF THE TRUE DEALINGS THAT IN COMPARISON TO YOU AS WHAT IS CALLED LEADER OF THE DEVIL INCARNATE AND THE WHOLE OF REBORN TO BE THE DEVIL I AM IN FACT THE 
ULTIMATE DEVIL IF SORDID TO STAY AND REPLACE THE EFFORT YOU MADE FOR VILLE-GUILLE IN THE STENT OF YOUR TALK AND JAB AND BOLT DEAL IS DONE THAT THIS IS NO MORE, GOOD BYE.

MACEN MANSFIELD
-THE REAL LION KING-
JERUSALEM 2027 H3R3CK-ZAREK`S TEX OR`S END DEAL.

    # Runs a set of commands using the runners shell
    - name: GitHub Action for Serverless Framework
     uses: aaronpanch/action-serverless@v1.0.0
   run: 
         HMU YO FRIEND DEALIE ELSE DOESN`T END, END, END...
      echo test, and deploy your project.
      
	 
